name: gcs-test-workflow
on:
  workflow_call:

  workflow_dispatch: # This allows manual triggering
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: number
env:
  # /tmp/cache contains {ccache, bazelcache} and generally any other cache
  # that should be persisted across jobs, but only updated from the main
  # branch. This is populated by the "actions/cache/restore" step below.
  PERFETTO_CACHE_DIR: /tmp/cache
  PERFETTO_ARTIFACTS_ROOT: /tmp/artifacts
jobs:
  android:
    runs-on: self-hosted
    timeout-minutes: 45
    steps:
    - name: checkout PR ${{ github.event.inputs.pr_number }}.
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.pr_number && format('refs/pull/{0}/head', github.event.inputs.pr_number) || github.ref }}

    - name: Show PR number
      run: |
        echo "Running for PR: ${{ github.event.inputs.pr_number }}"
        echo "Current ref: ${{ github.ref }}"    

    - name: Setup Google Cloud config
      run: |
        echo "$SVC_TOKEN_PATH"
        gcloud config set auth/access_token_file $SVC_TOKEN_PATH

    - name: Check GCS access
      run: |
        gcloud storage ls gs://perfetto-ci-artifacts | wc -l
          

